"""Enterprise DB Schema Init

Revision ID: 1fec52af46ad
Revises: 
Create Date: 2026-06-29 11:38:49.234901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fec52af46ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recording_url', sa.String(length=1024), nullable=True),
    sa.Column('transcript_status', sa.String(length=50), nullable=False),
    sa.Column('summary_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_deleted_at'), 'meetings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_table('participants',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('future_external_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_deleted_at'), 'participants', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_participants_email'), 'participants', ['email'], unique=True)
    op.create_index(op.f('ix_participants_future_external_id'), 'participants', ['future_external_id'], unique=False)
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_deleted_at'), 'tags', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('action_items',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('assignee_id', sa.String(), nullable=True),
    sa.Column('task', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_items_assignee_id'), 'action_items', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_action_items_deleted_at'), 'action_items', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_action_items_id'), 'action_items', ['id'], unique=False)
    op.create_index(op.f('ix_action_items_meeting_id'), 'action_items', ['meeting_id'], unique=False)
    op.create_table('future_conversations',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_future_conversations_deleted_at'), 'future_conversations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_future_conversations_id'), 'future_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_future_conversations_meeting_id'), 'future_conversations', ['meeting_id'], unique=False)
    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('speaking_time', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'participant_id', name='uix_meeting_participant')
    )
    op.create_index(op.f('ix_meeting_participants_deleted_at'), 'meeting_participants', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_meeting_participants_id'), 'meeting_participants', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_participants_meeting_id'), 'meeting_participants', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_participants_participant_id'), 'meeting_participants', ['participant_id'], unique=False)
    op.create_table('meeting_settings',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('playback_speed', sa.Float(), nullable=False),
    sa.Column('auto_scroll', sa.Boolean(), nullable=False),
    sa.Column('theme_preference', sa.String(length=20), nullable=False),
    sa.Column('transcript_font_size', sa.String(length=10), nullable=False),
    sa.Column('show_timestamp', sa.Boolean(), nullable=False),
    sa.Column('show_speaker_avatar', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_settings_deleted_at'), 'meeting_settings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_meeting_settings_id'), 'meeting_settings', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_settings_meeting_id'), 'meeting_settings', ['meeting_id'], unique=True)
    op.create_table('meeting_summaries',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('detailed_summary', sa.Text(), nullable=True),
    sa.Column('decision_summary', sa.Text(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('ai_model_used', sa.String(length=50), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('generation_duration', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_summaries_deleted_at'), 'meeting_summaries', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_meeting_summaries_id'), 'meeting_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_summaries_meeting_id'), 'meeting_summaries', ['meeting_id'], unique=True)
    op.create_table('meeting_tags',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'tag_id', name='uix_meeting_tag')
    )
    op.create_index(op.f('ix_meeting_tags_deleted_at'), 'meeting_tags', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_meeting_tags_id'), 'meeting_tags', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_tags_meeting_id'), 'meeting_tags', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_tags_tag_id'), 'meeting_tags', ['tag_id'], unique=False)
    op.create_table('topics',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_summary', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_topic_meeting_sequence', 'topics', ['meeting_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_topics_deleted_at'), 'topics', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_index(op.f('ix_topics_meeting_id'), 'topics', ['meeting_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('speaker_id', sa.String(), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('embedding_placeholder', sa.String(length=255), nullable=True),
    sa.Column('sentiment_placeholder', sa.String(length=50), nullable=True),
    sa.Column('keywords_placeholder', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['participants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transcript_meeting_sequence', 'transcript_segments', ['meeting_id', 'sequence_number'], unique=False)
    op.create_index('ix_transcript_meeting_start_time', 'transcript_segments', ['meeting_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_transcript_segments_deleted_at'), 'transcript_segments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_transcript_segments_id'), 'transcript_segments', ['id'], unique=False)
    op.create_index(op.f('ix_transcript_segments_meeting_id'), 'transcript_segments', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_transcript_segments_speaker_id'), 'transcript_segments', ['speaker_id'], unique=False)
    op.create_table('future_comments',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_future_comments_deleted_at'), 'future_comments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_future_comments_id'), 'future_comments', ['id'], unique=False)
    op.create_index(op.f('ix_future_comments_meeting_id'), 'future_comments', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_future_comments_segment_id'), 'future_comments', ['segment_id'], unique=False)
    op.create_table('future_conversation_messages',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['future_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_future_conversation_messages_conversation_id'), 'future_conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_future_conversation_messages_deleted_at'), 'future_conversation_messages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_future_conversation_messages_id'), 'future_conversation_messages', ['id'], unique=False)
    op.create_table('future_highlights',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_future_highlights_deleted_at'), 'future_highlights', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_future_highlights_id'), 'future_highlights', ['id'], unique=False)
    op.create_index(op.f('ix_future_highlights_meeting_id'), 'future_highlights', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_future_highlights_segment_id'), 'future_highlights', ['segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_future_highlights_segment_id'), table_name='future_highlights')
    op.drop_index(op.f('ix_future_highlights_meeting_id'), table_name='future_highlights')
    op.drop_index(op.f('ix_future_highlights_id'), table_name='future_highlights')
    op.drop_index(op.f('ix_future_highlights_deleted_at'), table_name='future_highlights')
    op.drop_table('future_highlights')
    op.drop_index(op.f('ix_future_conversation_messages_id'), table_name='future_conversation_messages')
    op.drop_index(op.f('ix_future_conversation_messages_deleted_at'), table_name='future_conversation_messages')
    op.drop_index(op.f('ix_future_conversation_messages_conversation_id'), table_name='future_conversation_messages')
    op.drop_table('future_conversation_messages')
    op.drop_index(op.f('ix_future_comments_segment_id'), table_name='future_comments')
    op.drop_index(op.f('ix_future_comments_meeting_id'), table_name='future_comments')
    op.drop_index(op.f('ix_future_comments_id'), table_name='future_comments')
    op.drop_index(op.f('ix_future_comments_deleted_at'), table_name='future_comments')
    op.drop_table('future_comments')
    op.drop_index(op.f('ix_transcript_segments_speaker_id'), table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_segments_meeting_id'), table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_segments_id'), table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_segments_deleted_at'), table_name='transcript_segments')
    op.drop_index('ix_transcript_meeting_start_time', table_name='transcript_segments')
    op.drop_index('ix_transcript_meeting_sequence', table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_topics_meeting_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_deleted_at'), table_name='topics')
    op.drop_index('ix_topic_meeting_sequence', table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_meeting_tags_tag_id'), table_name='meeting_tags')
    op.drop_index(op.f('ix_meeting_tags_meeting_id'), table_name='meeting_tags')
    op.drop_index(op.f('ix_meeting_tags_id'), table_name='meeting_tags')
    op.drop_index(op.f('ix_meeting_tags_deleted_at'), table_name='meeting_tags')
    op.drop_table('meeting_tags')
    op.drop_index(op.f('ix_meeting_summaries_meeting_id'), table_name='meeting_summaries')
    op.drop_index(op.f('ix_meeting_summaries_id'), table_name='meeting_summaries')
    op.drop_index(op.f('ix_meeting_summaries_deleted_at'), table_name='meeting_summaries')
    op.drop_table('meeting_summaries')
    op.drop_index(op.f('ix_meeting_settings_meeting_id'), table_name='meeting_settings')
    op.drop_index(op.f('ix_meeting_settings_id'), table_name='meeting_settings')
    op.drop_index(op.f('ix_meeting_settings_deleted_at'), table_name='meeting_settings')
    op.drop_table('meeting_settings')
    op.drop_index(op.f('ix_meeting_participants_participant_id'), table_name='meeting_participants')
    op.drop_index(op.f('ix_meeting_participants_meeting_id'), table_name='meeting_participants')
    op.drop_index(op.f('ix_meeting_participants_id'), table_name='meeting_participants')
    op.drop_index(op.f('ix_meeting_participants_deleted_at'), table_name='meeting_participants')
    op.drop_table('meeting_participants')
    op.drop_index(op.f('ix_future_conversations_meeting_id'), table_name='future_conversations')
    op.drop_index(op.f('ix_future_conversations_id'), table_name='future_conversations')
    op.drop_index(op.f('ix_future_conversations_deleted_at'), table_name='future_conversations')
    op.drop_table('future_conversations')
    op.drop_index(op.f('ix_action_items_meeting_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_deleted_at'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_assignee_id'), table_name='action_items')
    op.drop_table('action_items')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_deleted_at'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_future_external_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_email'), table_name='participants')
    op.drop_index(op.f('ix_participants_deleted_at'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_deleted_at'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
