"""Add Productivity Models

Revision ID: 9db4f8233b15
Revises: c02c338aab09
Create Date: 2026-06-29 12:24:59.940920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db4f8233b15'
down_revision: Union[str, None] = 'c02c338aab09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recent_activity',
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recent_activity_deleted_at'), 'recent_activity', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_recent_activity_id'), 'recent_activity', ['id'], unique=False)
    op.create_table('search_history',
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_deleted_at'), 'search_history', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_search_history_id'), 'search_history', ['id'], unique=False)
    op.create_index(op.f('ix_search_history_query'), 'search_history', ['query'], unique=False)
    op.create_table('bookmarks',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmarks_deleted_at'), 'bookmarks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_bookmarks_id'), 'bookmarks', ['id'], unique=False)
    op.create_index(op.f('ix_bookmarks_meeting_id'), 'bookmarks', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_segment_id'), 'bookmarks', ['segment_id'], unique=False)
    op.create_table('comments',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_deleted_at'), 'comments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_meeting_id'), 'comments', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_comments_segment_id'), 'comments', ['segment_id'], unique=False)
    op.create_table('highlights',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_highlights_deleted_at'), 'highlights', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_highlights_id'), 'highlights', ['id'], unique=False)
    op.create_index(op.f('ix_highlights_meeting_id'), 'highlights', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_highlights_segment_id'), 'highlights', ['segment_id'], unique=False)
    op.drop_index('ix_future_highlights_deleted_at', table_name='future_highlights')
    op.drop_index('ix_future_highlights_id', table_name='future_highlights')
    op.drop_index('ix_future_highlights_meeting_id', table_name='future_highlights')
    op.drop_index('ix_future_highlights_segment_id', table_name='future_highlights')
    op.drop_table('future_highlights')
    op.drop_index('ix_future_comments_deleted_at', table_name='future_comments')
    op.drop_index('ix_future_comments_id', table_name='future_comments')
    op.drop_index('ix_future_comments_meeting_id', table_name='future_comments')
    op.drop_index('ix_future_comments_segment_id', table_name='future_comments')
    op.drop_table('future_comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('future_comments',
    sa.Column('meeting_id', sa.VARCHAR(), nullable=False),
    sa.Column('segment_id', sa.VARCHAR(), nullable=True),
    sa.Column('author_id', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_future_comments_segment_id', 'future_comments', ['segment_id'], unique=False)
    op.create_index('ix_future_comments_meeting_id', 'future_comments', ['meeting_id'], unique=False)
    op.create_index('ix_future_comments_id', 'future_comments', ['id'], unique=False)
    op.create_index('ix_future_comments_deleted_at', 'future_comments', ['deleted_at'], unique=False)
    op.create_table('future_highlights',
    sa.Column('meeting_id', sa.VARCHAR(), nullable=False),
    sa.Column('segment_id', sa.VARCHAR(), nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), nullable=False),
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_future_highlights_segment_id', 'future_highlights', ['segment_id'], unique=False)
    op.create_index('ix_future_highlights_meeting_id', 'future_highlights', ['meeting_id'], unique=False)
    op.create_index('ix_future_highlights_id', 'future_highlights', ['id'], unique=False)
    op.create_index('ix_future_highlights_deleted_at', 'future_highlights', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_highlights_segment_id'), table_name='highlights')
    op.drop_index(op.f('ix_highlights_meeting_id'), table_name='highlights')
    op.drop_index(op.f('ix_highlights_id'), table_name='highlights')
    op.drop_index(op.f('ix_highlights_deleted_at'), table_name='highlights')
    op.drop_table('highlights')
    op.drop_index(op.f('ix_comments_segment_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_meeting_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_deleted_at'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_bookmarks_segment_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_meeting_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_deleted_at'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_search_history_query'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_deleted_at'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_recent_activity_id'), table_name='recent_activity')
    op.drop_index(op.f('ix_recent_activity_deleted_at'), table_name='recent_activity')
    op.drop_table('recent_activity')
    # ### end Alembic commands ###
