"""Add Meeting Management flags

Revision ID: d369080d5bd8
Revises: 1fec52af46ad
Create Date: 2026-06-29 11:48:43.747916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd369080d5bd8'
down_revision: Union[str, None] = '1fec52af46ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('meeting_type', sa.String(length=100), nullable=False, server_default='general'))
    op.add_column('meetings', sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('meetings', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_meetings_is_archived'), 'meetings', ['is_archived'], unique=False)
    op.create_index(op.f('ix_meetings_is_pinned'), 'meetings', ['is_pinned'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_is_pinned'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_is_archived'), table_name='meetings')
    op.drop_column('meetings', 'is_archived')
    op.drop_column('meetings', 'is_pinned')
    op.drop_column('meetings', 'meeting_type')
    # ### end Alembic commands ###
